// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx-MBk8QBG31PA5drVUamdsOyrbK-P_LA',
    appId: '1:102134984473:web:d31e050d58255dd7459f88',
    messagingSenderId: '102134984473',
    projectId: 'bookcart-c7f2f',
    authDomain: 'bookcart-c7f2f.firebaseapp.com',
    storageBucket: 'bookcart-c7f2f.firebasestorage.app',
    measurementId: 'G-EPCC186B4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEa62MdNbJspkd90ZGwCwZKXK7cPxNj9I',
    appId: '1:102134984473:android:f10eba1e27655cf2459f88',
    messagingSenderId: '102134984473',
    projectId: 'bookcart-c7f2f',
    storageBucket: 'bookcart-c7f2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUaqym2hMMsmIDDbtxlBEYjaMnGY0kfaA',
    appId: '1:102134984473:ios:9e797a8fcc675434459f88',
    messagingSenderId: '102134984473',
    projectId: 'bookcart-c7f2f',
    storageBucket: 'bookcart-c7f2f.firebasestorage.app',
    iosBundleId: 'com.app.bookcart.bookcart',
  );
}
